from fastapi import APIRouter, HTTPException, BackgroundTasks, Request
from fastapi.responses import StreamingResponse
from models import AgentChatRequest, AgentChatResponse, ChatSession, ChatMessage
from agent.core import invoke_agent_with_history, stream_agent_with_history
from agent.memory import get_all_sessions, delete_session, get_session_messages
from typing import List
import logging
import json

router = APIRouter(
    prefix="/agent",
    tags=["agent"],
    responses={404: {"description": "Not found"}},
)

logger = logging.getLogger(__name__)

@router.post("/chat", response_model=AgentChatResponse)
async def chat_with_agent(request: AgentChatRequest):
    """
    Interact with the AI agent.
    The agent has access to a sandboxed file system.
    Conversation history is automatically loaded and saved per session_id.
    """
    try:
        # Invoke agent with session history
        response = invoke_agent_with_history(request.message, request.session_id)
        
        return AgentChatResponse(
            response=response,
            session_id=request.session_id
        )

    except Exception as e:
        logger.error(f"Error in agent chat: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/chat/stream")
async def stream_chat_with_agent(
    request: AgentChatRequest, 
    request_obj: Request, 
    background_tasks: BackgroundTasks
):
    """
    Stream AI agent responses in real-time using Server-Sent Events.
    Each chunk is sent as it's generated by the LLM.
    """
    
    # Check if this is a new session (or has no messages yet)
    try:
        current_messages = get_session_messages(request.session_id)
        if len(current_messages) == 0:
            # It's a new session, set initial title and schedule AI naming
            from agent.memory import save_session_title
            from agent.core import generate_chat_title
            
            # Initial temporary title
            save_session_title(request.session_id, "New Chat")
            
            async def update_title_task(msg: str, sid: str):
                title = await generate_chat_title(msg)
                save_session_title(sid, title)
            
            background_tasks.add_task(update_title_task, request.message, request.session_id)
    except Exception as e:
        logger.error(f"Error checking session state: {e}")

    async def generate():
        try:
            async for chunk in stream_agent_with_history(request.message, request.session_id):
                # Check for client disconnection
                if await request_obj.is_disconnected():
                    logger.info("Client disconnected, stopping agent stream.")
                    break
                
                # Format as SSE: data: <content>\n\n
                yield f"data: {json.dumps({'content': chunk})}\n\n"
            
            # Signal end of stream if not disconnected
            if not await request_obj.is_disconnected():
                yield f"data: {json.dumps({'done': True})}\n\n"
        except Exception as e:
            logger.error(f"Streaming error: {e}", exc_info=True)
            yield f"data: {json.dumps({'error': str(e)})}\n\n"
    
    return StreamingResponse(
        generate(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no"
        }
    )


@router.get("/sessions", response_model=List[ChatSession])
async def list_sessions():
    """Get all chat sessions."""
    try:
        sessions = get_all_sessions()
        return [ChatSession(**s) for s in sessions]
    except Exception as e:
        logger.error(f"Error listing sessions: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/sessions/{session_id}/messages", response_model=List[ChatMessage])
async def get_messages(session_id: str):
    """Get all messages for a specific session."""
    try:
        messages = get_session_messages(session_id)
        return [ChatMessage(**m) for m in messages]
    except Exception as e:
        logger.error(f"Error getting messages: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/sessions", response_model=ChatSession)
async def create_chat_session(request: AgentChatRequest):
    """Create a new empty chat session."""
    try:
        from agent.memory import save_session_title
        
        # Ensure session doesn't already exist or handle re-use logic if needed
        # For now, we trust the ID passed from frontend or generate one
        session_id = request.session_id
        
        # Save initial title
        save_session_title(session_id, "New Chat")
        
        return ChatSession(
            session_id=session_id,
            message_count=0,
            title="New Chat"
        )
    except Exception as e:
        logger.error(f"Error creating session: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.delete("/sessions/{session_id}")
async def delete_chat_session(session_id: str):
    """Delete a specific chat session."""
    try:
        success = delete_session(session_id)
        if success:
            return {"message": "Session deleted", "session_id": session_id}
        else:
            raise HTTPException(status_code=404, detail="Session not found")
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error deleting session: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))
